# Generated by Django 4.1.1 on 2023-01-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
